pcl_node:
  ros__parameters:
    perception_topic: "/camera/pointcloud"
    camera_frame: "camera_color_optical_frame"
    point_cloud_params:
      passthrough_filter_limits_x: [-0.50, 0.50]
      passthrough_filter_limits_y: [-0.55, 0.40]
      passthrough_filter_limits_z: [0.01, 0.60]      
      segmentation_max_iterations: 50
      segmentation_distance_threshold: 0.001
      cluster_tolerance: 0.01
      min_cluster_size: 750
      cloud_normal_radius: 0.03
    end_effectors:
      end_effector_names: [robotiq_2f, suction_cup]
      robotiq_2f:
        type: finger
        num_fingers: 2
        finger_thickness: 0.02
        distance_between_fingers: 0.10
        grasp_planning_params:
          grasp_plane_dist_limit: 0.007
          voxel_size: 0.01
          grasp_rank_weight_1: 1.5
          grasp_rank_weight_2: 1.0
          world_x_angle_threshold: 0.5
          world_y_angle_threshold: 0.5
          world_z_angle_threshold: 0.25
      suction_cup:
        type: suction
        num_cups_length: 5
        num_cups_breadth: 3
        cup_radius: 0.01
        cup_height: 0.01
        grasp_planning_params:
          num_sample_along_axis: 5
          search_resolution: 0.01
          search_angle_resolution: 4
          weights:
            curvature: 1.0
            grasp_distance_to_center: 1.0
            number_contact_points: 1.0
          
      
