robot:
  name: panda
  brand: panda_robot
  filepath: /home/rosi5/emd_ws/src/assets/robots/panda_description
  base_link: panda_link0
  ee_link: panda_hand
  links:
    - panda_link0
    - panda_link1
    - panda_link2
    - panda_link3
    - panda_link4
    - panda_link5
    - panda_link6
    - panda_link7
    - panda_link8
    - panda_hand
    - panda_leftfinger
    - panda_rightfinger
objects:
  table:
    child_link: table
    links:
      table:
        visual:
          name: table
          geometry:
            filepath: /home/rosi/error_check_ws/src/assets/environment/table_description/meshes/visual/table.stl
            scale:
              scale_x: 0.001
              scale_y: 0.001
              scale_z: 0.001
        collision:
          name: None
          geometry:
            filepath: /home/rosi/error_check_ws/src/assets/environment/table_description/meshes/visual/table.stl
            scale:
              scale_x: 0.001
              scale_y: 0.001
              scale_z: 0.001
    table_base_joint:
      ext_joint_type: fixed
      child_link: table
external joints:
  table:
    parent object: world
    parent link: world